### ISSUE TITLE
Awakened Ichorium Pickaxe and Bedrock Dimension Bug

### ISSUE THREAD

**Issue by Glenn-Diamond** [Thaumic-Tinkerer/ThaumicTinkerer#730]
Awakened Ichorium Pickaxe:
The Awakened Ichorium Pickaxe Has an issue mining only one single block regardless of what mode it's on however this issue, from what I've seen, only happens when mining bedrock in the Bedrock Dimension.

Bedrock Dimension:
Using the Awakened Ichorium Pickaxe, the player can mine past the ceiling and actually collect bedrock.

![2015-04-24_21 29 52](https://cloud.githubusercontent.com/assets/12108132/7331661/bc24ac78-eace-11e4-86db-786ac92a72a1.png)

**Comment by Magiks21** [comment]
Issue was fixed
#719

**Comment by Meegooo** [comment]
Actually, issue still exists.
Using build 503, forge 1420 and i'm still able to mine bedrock like this.
And also line and square mining modes don't work with bedrock. Pick just mines 1 block at a time.
